#define ORYX_CONFIGURATOR
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPSH

#define PERMISSIVE_HOLD

#undef DEBOUNCE
#define DEBOUNCE 45

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 300