LINK_TIME_OPTIMIZATION_ENABLE = yes
COMMAND_ENABLE = no
# SRC = matrix.c
# RGBLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = yes

# DEBOUNCE_TYPE = sym_g
DEBOUNCE_TYPE = eager_pk

LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes